on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: build-on-pr

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/setup-sam@v2
      - name: SAM Build
        run: sam build
